### ISSUE TITLE
Discord invitation link expired

### ISSUE THREAD

**Issue by sasspaper** [EngineTribe/EngineTribe#5]

**Comment by chiyuki0325** [comment]
First, the official Engine Kingdom community has been disbanded long after the game's original creator, Franyer, stopped updating the game. Moreover, the new Engine Kingdom community formed by the players has changed hands and is now **not affiliated to this project** in any way.

**Comment by chiyuki0325** [comment]
At present, the player group of SMM:WE has been severely divided, and the games continued by the community have already been divided into multiple branches. There is no real "official".
And due to this divisive situation, this project has also been discontinued lol

**Comment by chiyuki0325** [comment]
As for the twitter account... I don't know who is controlling it now, sorry.

**Comment by boobthecat** [comment]
Sorry for my hostility, and thank god I found a working [link](https://discord.com/invite/YwpyCfHgSr).
